// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Data;

#nullable disable

namespace ProjectBE.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221210192055_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("Project.Models.Course", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CODE")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CREATEDDATE")
                        .HasColumnType("TEXT");

                    b.Property<string>("CREATEDUSER")
                        .HasColumnType("TEXT");

                    b.Property<string>("DESCRIPTION")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ENDDATE")
                        .HasColumnType("TEXT");

                    b.Property<string>("NAME")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("STARTDATE")
                        .HasColumnType("TEXT");

                    b.Property<string>("STATUS")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Project.Models.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CODE")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CREATEDDATE")
                        .HasColumnType("TEXT");

                    b.Property<string>("EMAIL")
                        .HasColumnType("TEXT");

                    b.Property<string>("IDENTIFY")
                        .HasColumnType("TEXT");

                    b.Property<string>("NAME")
                        .HasColumnType("TEXT");

                    b.Property<string>("PHONE")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<int>("SEX")
                        .HasColumnType("INTEGER");

                    b.Property<string>("STATUS")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Project.Models.Group", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CODE")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CREATEDDATE")
                        .HasColumnType("TEXT");

                    b.Property<string>("CREATEDUSER")
                        .HasColumnType("TEXT");

                    b.Property<string>("DESCRIPTION")
                        .HasColumnType("TEXT");

                    b.Property<string>("NAME")
                        .HasColumnType("TEXT");

                    b.Property<string>("STATUS")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Project.Models.JoinCourse", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IDCOURSE")
                        .HasColumnType("TEXT");

                    b.Property<string>("IDMEMBER")
                        .HasColumnType("TEXT");

                    b.Property<string>("TITLE")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("JoinCourses");
                });

            modelBuilder.Entity("Project.Models.JoinGroup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IDCOURSE")
                        .HasColumnType("TEXT");

                    b.Property<string>("IDMEMBER")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("JoinGroups");
                });

            modelBuilder.Entity("Project.Models.Staff", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CODE")
                        .HasColumnType("TEXT");

                    b.Property<string>("EMAIL")
                        .HasColumnType("TEXT");

                    b.Property<string>("IDENTIFY")
                        .HasColumnType("TEXT");

                    b.Property<int>("LEVEL")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NAME")
                        .HasColumnType("TEXT");

                    b.Property<string>("PHONE")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<int>("SEX")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("STARTWORKDATE")
                        .HasColumnType("TEXT");

                    b.Property<string>("STATUS")
                        .HasColumnType("TEXT");

                    b.Property<string>("TITLE")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Staffs");
                });
#pragma warning restore 612, 618
        }
    }
}
