// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Data;

#nullable disable

namespace ProjectBE.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230203011504_update_article_model")]
    partial class update_article_model
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("Project.Models.Articles", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ARTICLE_CONTENT")
                        .HasColumnType("TEXT");

                    b.Property<string>("AVATAR")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CREATE_DATE")
                        .HasColumnType("TEXT");

                    b.Property<int>("CREATE_USER")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HASTAG")
                        .HasColumnType("TEXT");

                    b.Property<string>("LANGUAGE")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LATEST_EDIT_DATE")
                        .HasColumnType("TEXT");

                    b.Property<int>("LATEST_EDIT_USER")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PRIORITY_LEVEL")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SUMMARY")
                        .HasColumnType("TEXT");

                    b.Property<string>("TITLE")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("Project.Models.Hastag", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CODE")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Hastag");
                });

            modelBuilder.Entity("Project.Models.Menu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DESCRIPTION")
                        .HasColumnType("TEXT");

                    b.Property<string>("HASTAG")
                        .HasColumnType("TEXT");

                    b.Property<int>("MENU_LEVEL")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("Project.Models.Role", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CODE")
                        .HasColumnType("TEXT");

                    b.Property<string>("RULE_LIST")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Project.Models.Rule", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CODE")
                        .HasColumnType("TEXT");

                    b.Property<string>("DESCRIPTION")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Rule");
                });

            modelBuilder.Entity("Project.Models.Staff", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CODE")
                        .HasColumnType("TEXT");

                    b.Property<string>("EMAIL")
                        .HasColumnType("TEXT");

                    b.Property<string>("NAME")
                        .HasColumnType("TEXT");

                    b.Property<string>("PASSWORD")
                        .HasColumnType("TEXT");

                    b.Property<string>("PASSWORDHASH")
                        .HasColumnType("TEXT");

                    b.Property<string>("PASSWORDSALT")
                        .HasColumnType("TEXT");

                    b.Property<string>("PHONE")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ROLE_ID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("USERNAME")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Staffs");
                });
#pragma warning restore 612, 618
        }
    }
}
